# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: echo "Starting Build Process"
  displayName: 'Start Build'

- script: dotnet restore
  displayName: 'Restore NuGet Packages'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'

- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'Run Tests'

- script: echo "Build Process Completed"
  displayName: 'End Build'

